--- # text file
- name: install apache
  action: yum name=httpd state=present
- name: start apache
  action: service name=httpd state=started
- name: copy index.html
  action: copy 
      src=index.html dest=/var/www/html/
  notify: restart
